Switched to C++14 to allow to compile hash_djb2a().
With C++11 there's:
error: 'auto' return without trailing return type; deduced return types are a C++14 extension